error

diff --git a/.github/workflows/workflow1.yml b/.github/workflows/workflow1.yml
--- a/.github/workflows/workflow1.yml
+++ b/.github/workflows/workflow1.yml
@@ -16,6 +16,6 @@ jobs:
     # Job's steps
     steps:
       # Check-out your repository
-      - uses: actions/checkout@v3
-      - name: Run a one-liner script
-        run: echo "Continuous Integration"
+      - uses: actions/checkout@v4
+      - name: To Show Error
+        run: echo "Should fail at this point..."; exit 1
